CREATE TABLE CLIENTES(
CORREO VARCHAR(100),
DIRECCION_ENVIO VARCHAR(150),
NOMBRE_COMPLETO VARCHAR(100),
NUMERO_TELEFONO DECIMAL(9),
CONSTRAINT PK_CorreoCliente PRIMARY KEY (CORREO)
);

CREATE TABLE PINTORES(
CORREO VARCHAR(100),
FECHA_DE_NACIMIENTO DATE,
NOMBRE_COMPLETO VARCHAR(100),
CANTIDAD_DE_OBRAS DECIMAL(2),
ESTILO VARCHAR(50),
CONSTRAINT PK_CorreoPintor PRIMARY KEY (CORREO)
);

CREATE TABLE OBRAS(
TITULO VARCHAR(100),
CORREO_AUTOR VARCHAR(100),
TEMATICA VARCHAR(50),
FECHA_INICIO DATE,
FECHA_FIN DATE,
CANTIDAD_DISPONIBLE DECIMAL(2),
CANTIDAD_CREADA DECIMAL (2),
DIMENSION_X DECIMAL(3),
DIMENSION_Y DECIMAL(3),
PRECIO DECIMAL(8,2),
CONSTRAINT PK_Obras PRIMARY KEY (TITULO,CORREO_AUTOR),
CONSTRAINT FK_Obras_CorreoAutor FOREIGN KEY (CORREO_AUTOR) REFERENCES PINTORES(CORREO)
);

CREATE TABLE COMPRAS(
ID_COMPRA INT(5) AUTO_INCREMENT,
CORREO_CLIENTE VARCHAR(100),
IMPORTE_TOTAL DECIMAL(8,2),
FECHA_COMPRA DATE,
NUMERO_OBRAS_COMPRADAS DECIMAL(2),
CONSTRAINT PK_Compras PRIMARY KEY (ID_COMPRA),
CONSTRAINT FK_Compras_CorreoCliente FOREIGN KEY (CORREO_CLIENTE) REFERENCES CLIENTES(CORREO)
);

CREATE TABLE OBRAS_COMPRADAS(
TITULO_OBRA VARCHAR(100),
CORREO_AUTOR VARCHAR(100),
ID_COMPRA INT(5),
PRECIO_COMPRA DECIMAL(6,2),
CANTIDAD_COMPRADA DECIMAL(2),
CONSTRAINT PK_ObrasCompradas PRIMARY KEY (TITULO_OBRA,CORREO_AUTOR,ID_COMPRA),
CONSTRAINT FK_ObrasCompradas_Titulo FOREIGN KEY (TITULO_OBRA) REFERENCES OBRAS(TITULO),
CONSTRAINT FK_ObrasCompradas_IdCompra FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS(ID_COMPRA),
CONSTRAINT FK_ObrasCompradas_CorreoAutor FOREIGN KEY (CORREO_AUTOR) REFERENCES OBRAS(CORREO_AUTOR)
);