<?php
include_once "databaseManagerClass.php";

class ordersDatabaseManager extends DatabaseManager
{
  function __construct()
  {
    parent::__construct();
  }

  // Returns a order with the autogenerated order_id
  // property
  public function insert_order(Order $order): Order
  {
    $stmt = $this->mysqli->prepare(
      "INSERT INTO ORDERS(client_email, total_charge, order_date, total_artworks_adquired) VALUES(?,?,?,?)"
    );

    $stmt->bind_param(
      "sdsi",
      $client_email,
      $total_charge,
      $order_date,
      $total_artworks_adquired
    );

    $client_email = $order->get_client_email();
    $total_charge = $order->get_total_charge();
    $order_date = $order->get_order_date();
    $total_artworks_adquired = $order->get_total_artworks_adquired();

    $stmt->execute();

    $order->set_order_id($stmt->insert_id);

    $stmt->close();

    return $order;
  }

  public function update_order_status(Order $order)
  {
    $order_id = $order->get_order_id();
    $order_status = $order->get_status();

    $stmt = $this->mysqli->prepare(
      "UPDATE ORDERS SET status = '" .
        $order_status .
        "' WHERE order_id =" .
        $order_id
    );

    $update_result = $stmt->execute();
    $stmt->close();

    if (!$update_result) {
      throw new Exception("Error updating order status", 1);
    }
  }

  /*
    Probably useful function in a future
    can delete if not
  */

  // public function select_order_by_id(string $order_id): Order
  // {
  //   $query = "SELECT * FROM ORDERS WHERE order_id = " . $order_id;

  //   $row = $this->mysqli->query($query);

  //   if ($row) {
  //     $data = $row->fetch_array(MYSQLI_ASSOC);

  //     $order = new Order($data[""], $data[""], $data[""], $data[""], $data[""]);
  //   }
  // }
}
